### ISSUE TITLE
Developer install failed for me

### ISSUE THREAD

**Issue by jefffranks** [WRidder/react-spa#11]
Hi,

I'm fairly new to web programming and react.js but wanted to try out the react-spa project.
Just did a git clone on react-spa into my local directory on a Linux Mint-17 machine.
I have an install issue relative to the "For developers" first step -- it fails.

Is there something I can do to fix this?
Please let me know.

"Just running the demo" installed okay, worked and produced an empty page with
 the title of the web app. Is that the expectation?

For developers, "$ npm install" in the base directory failed.
  Last part of console output is below where the errors show up.
  Could not figure out how to attach npm-debug.log

I'm using the following components:

$ node --version
v0.12.2
$ npm --version
2.8.3

-------console output------------
  [496] ./client/src/mixins/approveTransition.js 366 bytes {0} [built]
  [497] ./client/src/components/markdown/editor.jsx 2.65 kB {0} [built]
  [498] ./client/src/components/questions/questionNotFound.jsx 519 bytes {0} [built]
  [499] ./client/src/components/discussions/discussions.jsx 1.44 kB {0} [built]
[09:11:02] Finished 'bundle' after 14 s
[09:11:02] Finished 'build' after 15 s
npm ERR! Linux 3.13.0-37-generic
npm ERR! argv "node" "/home/jfranks/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.8.3
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer material-ui@0.7.5 wants react@>=0.13
npm ERR! peerinvalid Peer react-document-title@1.0.2 wants react@>=0.11.0 || >=0.13.0-beta.1
npm ERR! peerinvalid Peer react-router@0.12.4 wants react@0.12.x
npm ERR! peerinvalid Peer react-tap-event-plugin@0.1.7 wants react@~0.13.x || ~0.12.x

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jfranks/Desktop/react-spa/npm-debug.log
----------------------------

**Comment by WRidder** [comment]
Hi Jeff. Thanks for the heads up! It seems to me that there is an issue with peer dependencies (react 0.12 vs 0.13). Should be easy to fix but I won't get around looking into it until this weekend I'm afraid. 

I'll give you an update once I know more!

**Comment by jefffranks** [comment]
Hi WRidder,

Since I was having issues with a different project that uses react, the resolution to that was NOT
use node v0.12.2. So, I un-installed node and re-installed node v0.10.33. npm was removed also and re-installed as v2.11.1

I was hoping that this might resolve the issue with this project.
So, I decided to try from scratch w/ git clone and start over with this project with the older version of node and npm. Well, that did not help. The issue remains as before. The console log shows the same result as follows:

======= console log ============
  [497] ./client/src/components/markdown/editor.jsx 2.65 kB {0} [built]
  [498] ./client/src/components/questions/questionNotFound.jsx 519 bytes {0} [built]
  [499] ./client/src/components/discussions/discussions.jsx 1.44 kB {0} [built]
[15:48:10] Finished 'bundle' after 15 s
[15:48:10] Finished 'build' after 16 s
npm ERR! Linux 3.13.0-37-generic
npm ERR! argv "node" "/home/jfranks/local/bin/npm" "install"
npm ERR! node v0.10.33
npm ERR! npm  v2.11.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer material-ui@0.7.5 wants react@>=0.13
npm ERR! peerinvalid Peer react-document-title@1.0.2 wants react@>=0.11.0 || >=0.13.0-beta.1
npm ERR! peerinvalid Peer react-router@0.12.4 wants react@0.12.x
npm ERR! peerinvalid Peer react-tap-event-plugin@0.1.7 wants react@~0.13.x || ~0.12.x

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jfranks/Desktop/ws2 - react-spa/react-spa/npm-debug.log
========================

**Comment by WRidder** [comment]
Alright, the issue was fairly simple. Material-ui required react 0.13 within a minor version update. That in combination with non-exact versions in the package.json caused incompatibility. Solution for now is to force exact versions in the package.json as just has been committed.

Can you try again and report back whether it works?

**Comment by jefffranks** [comment]
Hi WRidder,

Issue IS RESOLVED. This now works and is okay.
Thank you for your hard work on this.

**Comment by WRidder** [comment]
You're welcome! If you have any questions or encounter issues; let me know!
