### ISSUE TITLE
Online demo?

### ISSUE THREAD

**Issue by winkler1** [WRidder/react-spa#4]
Hi-
 Just found this from the reflux ticket. Looks really good and I'll be keen to watch your learnings.
 Question - does this lend itself to an online demo, or is that a pain because of the server component? Would like to add to react.rocks, like to have tangible demos for people to play with.

**Comment by WRidder** [comment]
@winkler1, @hpaul: Demo app is online here: [http://react-spa.herokuapp.com/](http://react-spa.herokuapp.com/). Thanks for the suggestion.

**Comment by WRidder** [comment]
Added automatic deployment from travis to heroku as well. On every commit of this repo, if the build succeeds it's automatically deployed to the heroku app.

**Comment by winkler1** [comment]
nice!

On Tue, Jan 6, 2015 at 7:51 AM, Wilbert van de Ridder <
notifications@github.com> wrote:

> Added automatic deployment from travis to heroku as well. On every commit
> of this repo, if the build succeeds it's automatically deployed to the
> heroku app.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WRidder/react-spa/issues/4#issuecomment-68861264>.
>



-- 
http://twitter.com/#!/winkler1
Co-organizer, ReactJS Boston <http://www.meetup.com/ReactJS-Boston/>

**Comment by winkler1** [comment]
Are you on twitter? ... adding to react.rocks, want to mention author if so.

**Comment by WRidder** [comment]
@winkler1 Yep, see `@techwuppet`
