### ISSUE TITLE
Structure the src folder

### ISSUE THREAD

**Issue by captDaylight** [WRidder/react-spa#7]
First, I want to say great work on creating this resource. It's been really helpful.

My one thing, the src folder could be more structured, right now there is one level of hierarchy. Folders like styles, tests, and assets are mixed in with your application folders like routes, actions, and stores. It will make it easier for someone from the outside looking in to jump into the code quicker.

**Comment by WRidder** [comment]
@captDaylight Thanks for the feedback! I'll look into it. Any particular suggestions for the folder structure you have in mind?

**Comment by WRidder** [comment]
I was thinking somethings like:
- server
- client
  - src
    - actions
    - stores
    - etc.
  - styles
  - assets
  - template
  - etc.

**Comment by captDaylight** [comment]
ya totally, I think that would be great. I'm sure you are thinking this, but app.js would be at the root of src/  so you can see how src is initialized. :thumbsup:

**Comment by WRidder** [comment]
Just updated the folder structure, let me know what you think! :)
