### ISSUE TITLE
logout - http get ?

### ISSUE THREAD

**Issue by FredericHeem** [WRidder/react-spa#8]
For security reason, "auth/logout" should not used a http get but a http post.

**Comment by WRidder** [comment]
@FredericHeem Thanks for the heads up. Will look into it immediatly.

**Comment by WRidder** [comment]
And can you elaborate on the reason?

**Comment by WRidder** [comment]
I did find some background here: http://stackoverflow.com/questions/15051712/how-to-do-authentication-with-a-rest-api-right-browser-native-clients

**Comment by FredericHeem** [comment]
http://stackoverflow.com/questions/3521290/logout-get-or-post

**Comment by WRidder** [comment]
Updated, thanks @FredericHeem.

One think I'm noticing is that in Firefox (not present in Chrome) an error is logged in the console when logging out. However, it's not related to the client, it seems to originate from the `post` response. Any ideas what the standard response should be? At the moment in express the response is just ended with a 200 success.

**Comment by FredericHeem** [comment]
Thanks for the quick fix.
